version: '3.8'
services:
  mongodb:
    image: mongo:4.4.7
    container_name: mongodb
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    expose:
      - ${DB_LOCAL_PORT}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
